[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
student_intro = "EZVdGWwx3FTorwSFJFWw12BZRdevcqro4vs1Vm9NTg7Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sebatustra/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
